version: "3.8"

services:
  app:
    build: .
    ports:
      - 3000:5111
    volumes:
      - .:/app:ro
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017
